<a href="https://colab.research.google.com/github/sakshijadhav-08/aiml-assignments-1920/blob/main/20_A.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as ply
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import StandardScaler

In [2]:
ds = pd.read_csv("ford_car_dataset.csv")

In [22]:
ds.shape

(17812, 9)

In [23]:
ds.isnull().sum()

model           0
year            0
price           0
transmission    0
mileage         0
fuelType        0
tax             0
mpg             0
engineSize      0
dtype: int64

In [25]:
ds.describe()

,year,price,mileage,tax,mpg,engineSize
count,17812.000000,17812.000000,17812.000000,17812.000000,17812.000000,17812.000000
mean,2016.862396,12269.556310,23381.146362,113.315012,57.908696,1.350623
std,2.052039,4736.285417,19419.011045,62.034603,10.132696,0.432581
min,1996.000000,495.000000,1.000000,0.000000,20.800000,0.000000
25%,2016.000000,8999.000000,10000.000000,30.000000,52.300000,1.000000
50%,2017.000000,11288.000000,18277.000000,145.000000,58.900000,1.200000
75%,2018.000000,15295.000000,31098.500000,145.000000,65.700000,1.500000
max,2060.000000,54995.000000,177644.000000,580.000000,201.800000,5.000000

In [26]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
Index: 17812 entries, 0 to 17965
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   model         17812 non-null  object
 1   year          17812 non-null  int64
 2   price         17812 non-null  int64
 3   transmission  17812 non-null  object
 4   mileage       17812 non-null  int64
 5   fuelType      17812 non-null  object
 6   tax           17812 non-null  int64
 7   mpg           17812 non-null  float64
 8   engineSize    17812 non-null  float64
dtypes: float64(2), int64(4), object(3)
memory usage: 1.4+ MB

In [17]:
ds.duplicated().sum()

np.int64(154)

In [20]:
ds.drop_duplicates(inplace=True)

In [21]:
ds.duplicated().sum()

np.int64(0)

In [3]:
X = ds.drop("price", axis=1)
Y = ds["price"]
X.shape

(17966, 8)

In [4]:
Y.shape

(17966,)

In [5]:
X = pd.get_dummies(X, dtype=int)

print(X.head())

   year  mileage  tax   mpg  engineSize  model_ B-MAX  model_ C-MAX  \
0  2017    15944  150  57.7         1.0             0             0
1  2018     9083  150  57.7         1.0             0             0
2  2017    12456  150  57.7         1.0             0             0
3  2019    10460  145  40.3         1.5             0             0
4  2019     1482  145  48.7         1.0             0             0

   model_ EcoSport  model_ Edge  model_ Escort  ...  model_ Transit Tourneo  \
0                0            0              0  ...                       0
1                0            0              0  ...                       0
2                0            0              0  ...                       0
3                0            0              0  ...                       0
4                0            0              0  ...                       0

   model_Focus  transmission_Automatic  transmission_Manual  \
0            0                       1                    0
1            0                       0                    1
2            0                       0                    1
3            0                       0                    1
4            0                       1                    0

   transmission_Semi-Auto  fuelType_Diesel  fuelType_Electric  \
0                       0                0                  0
1                       0                0                  0
2                       0                0                  0
3                       0                0                  0
4                       0                0                  0

   fuelType_Hybrid  fuelType_Other  fuelType_Petrol
0                0               0                1
1                0               0                1
2                0               0                1
3                0               0                1
4                0               0                1

[5 rows x 37 columns]

In [6]:
scaler = StandardScaler()

num_cols = ["year", "mileage", "tax", "mpg", "engineSize"]

X[num_cols] = scaler.fit_transform(X[num_cols])

print(X.head())

       year   mileage       tax       mpg  engineSize  model_ B-MAX  \
0  0.065128 -0.380998  0.591358 -0.020442   -0.811386             0
1  0.552866 -0.733359  0.591358 -0.020442   -0.811386             0
2  0.065128 -0.560132  0.591358 -0.020442   -0.811386             0
3  1.040605 -0.662640  0.510727 -1.738890    0.345070             0
4  1.040605 -1.123724  0.510727 -0.909294   -0.811386             0

   model_ C-MAX  model_ EcoSport  model_ Edge  model_ Escort  ...  \
0             0                0            0              0  ...
1             0                0            0              0  ...
2             0                0            0              0  ...
3             0                0            0              0  ...
4             0                0            0              0  ...

   model_ Transit Tourneo  model_Focus  transmission_Automatic  \
0                       0            0                       1
1                       0            0                       0
2                       0            0                       0
3                       0            0                       0
4                       0            0                       1

   transmission_Manual  transmission_Semi-Auto  fuelType_Diesel  \
0                    0                       0                0
1                    1                       0                0
2                    1                       0                0
3                    1                       0                0
4                    0                       0                0

   fuelType_Electric  fuelType_Hybrid  fuelType_Other  fuelType_Petrol
0                  0                0               0                1
1                  0                0               0                1
2                  0                0               0                1
3                  0                0               0                1
4                  0                0               0                1

[5 rows x 37 columns]

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, Y,test_size=0.33,random_state=42)
X_train
X_test

,year,mileage,tax,mpg,engineSize,model_ B-MAX,model_ C-MAX,model_ EcoSport,model_ Edge,model_ Escort,...,model_ Transit Tourneo,model_Focus,transmission_Automatic,transmission_Manual,transmission_Semi-Auto,fuelType_Diesel,fuelType_Electric,fuelType_Hybrid,fuelType_Other,fuelType_Petrol
17610,-1.398088,-0.080611,-1.827578,0.769650,-0.811386,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,1
7076,0.065128,0.290547,0.591358,0.769650,-0.811386,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,1
1713,-0.910349,1.170551,-1.505053,0.927668,0.576362,0,0,0,0,0,...,0,0,0,1,0,1,0,0,0,0
1611,-1.885826,1.010368,-1.343791,-0.247593,-0.811386,1,0,0,0,0,...,0,0,0,1,0,0,0,0,0,1
16830,-3.836780,2.857374,1.397670,-0.909294,1.038944,0,0,0,0,0,...,0,0,0,1,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6015,1.040605,-0.908538,0.510727,1.253580,1.501527,0,0,0,0,0,...,0,0,0,1,0,1,0,0,0,0
10301,-0.422611,-0.746198,-1.827578,-0.020442,-0.811386,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
15006,1.040605,-0.812089,0.510727,-2.845018,0.345070,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1
5396,-1.885826,1.645552,0.752620,-1.363597,0.576362,1,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
6087,-0.422611,-0.049488,0.188202,-0.553753,-0.811386,0,0,1,0,0,...,0,0,0,1,0,0,0,0,0,1

In [9]:
y_train
y_test

17610     6995
7076      8999
1713      7998
1611      5491
16830     3790
         ...
6015     19000
10301    10940
15006    21999
5396      6995
6087     10299
Name: price, Length: 5929, dtype: int64

In [10]:
lr = LinearRegression()

lr.fit(X_train, y_train)

print("Intercept :", lr.intercept_)
print("Coefficients :")
print(lr.coef_)

Intercept : 16624.42763578743
Coefficients :
[ 2.14740256e+03 -1.32532970e+03 -6.27759124e+01 -8.20353166e+02
  1.08356730e+03 -4.02639412e+03 -2.92796686e+03 -2.35926570e+03
  5.53724546e+03  9.97603894e+03 -2.84721223e+03 -7.96862146e+02
 -3.36031565e+02  2.56961644e+03 -2.53006215e+03  5.09726763e+01
 -4.25957681e+03 -6.87550273e+03 -2.82962359e+02 -1.03438708e+03
  8.20550001e+03  3.71333848e+03  1.59161573e-11  2.37523965e+03
  4.54747351e-13 -4.98969646e+02  2.69783164e+03 -2.30983633e+03
 -4.04075355e+03  1.84573692e+02 -2.41088798e+02  5.65151064e+01
 -2.16206602e+03  0.00000000e+00  5.99557104e+03 -1.26539633e+03
 -2.56810869e+03]

In [11]:
y_pred = lr.predict(X_test)

print("Predicted Values")
print(y_pred[:10])

print("\nActual Values")
print(y_test.iloc[:10])

Predicted Values
[ 6676.74792864  9175.10363172  9876.15109278  3808.41679254
  2944.77931074 16623.10788236 27571.14532174 12128.40953688
 11577.4693611  16774.32274028]

Actual Values
17610     6995
7076      8999
1713      7998
1611      5491
16830     3790
14735    18200
322      22998
8164     11000
6822      7600
2133     14985
Name: price, dtype: int64

In [12]:
score = r2_score(y_test, y_pred)

score

0.8408137113174078

The R² score tells us how well the model predicts car prices. A value closer to 1 means better performance. If the score is high, the model is able to explain most of the variation in the dataset.

In [14]:
import joblib

joblib.dump(lr, "LR_ford_car.pkl")
joblib.dump(scaler, "scaler.pkl")
joblib.dump(X.columns.tolist(), "columns.pkl")

['columns.pkl']

In [27]:
lr

LinearRegression()