<a href="https://colab.research.google.com/github/sakshijadhav-08/aiml-assignments-1920/blob/main/20_OptionalTask.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [69]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
import joblib

In [70]:
from google.colab import files
uploaded = files.upload()

Saving Luxury_Scent_Analysis.csv to Luxury_Scent_Analysis (1).csv

In [71]:
filepath = '/content/Luxury_Scent_Analysis.csv'
df = pd.read_csv(filepath)

In [72]:
df.head()

,brand,title,type,price,priceWithCurrency,available,availableText,sold,lastUpdated,itemLocation
0,Dior,Christian Dior Sauvage Men's EDP 3.4 oz Fragra...,Eau de Parfum,84.99,US $84.99/ea,10.0,More than 10 available / 116 sold,116.0,"May 24, 2024 10:03:04 PDT","Allen Park, Michigan, United States"
1,AS SHOW,A-v-entus Eau de Parfum 3.3 oz 100ML Millesime...,Eau de Parfum,109.99,US $109.99,8.0,8 available / 48 sold,48.0,"May 23, 2024 23:07:49 PDT","Atlanta, Georgia, Canada"
2,Unbranded,HOGO BOSS cologne For Men 3.4 oz,Eau de Toilette,100.00,US $100.00,10.0,More than 10 available / 27 sold,27.0,"May 22, 2024 21:55:43 PDT","Dearborn, Michigan, United States"
3,Giorgio Armani,Acqua Di Gio by Giorgio Armani 6.7 Fl oz Eau D...,Eau de Toilette,44.99,US $44.99/ea,2.0,2 available / 159 sold,159.0,"May 24, 2024 03:30:43 PDT","Reinholds, Pennsylvania, United States"
4,Lattafa,Lattafa Men's Hayaati Al Maleky EDP Spray 3.4 ...,Fragrances,16.91,US $16.91,NaN,Limited quantity available / 156 sold,156.0,"May 24, 2024 07:56:25 PDT","Brooklyn, New York, United States"

In [73]:
df.shape

(1000, 10)

In [74]:
df.columns

Index(['brand', 'title', 'type', 'price', 'priceWithCurrency', 'available',
       'availableText', 'sold', 'lastUpdated', 'itemLocation'],
      dtype='object')

In [76]:
df.dtypes

brand                 object
title                 object
type                  object
price                float64
priceWithCurrency     object
available            float64
availableText         object
sold                 float64
lastUpdated           object
itemLocation          object
dtype: object

In [77]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   brand              999 non-null    object
 1   title              1000 non-null   object
 2   type               997 non-null    object
 3   price              1000 non-null   float64
 4   priceWithCurrency  1000 non-null   object
 5   available          889 non-null    float64
 6   availableText      997 non-null    object
 7   sold               994 non-null    float64
 8   lastUpdated        947 non-null    object
 9   itemLocation       1000 non-null   object
dtypes: float64(3), object(7)
memory usage: 78.3+ KB

In [78]:
df.isnull().sum()

brand                  1
title                  0
type                   3
price                  0
priceWithCurrency      0
available            111
availableText          3
sold                   6
lastUpdated           53
itemLocation           0
dtype: int64

In [79]:
df['brand'] = df['brand'].fillna('Unknown')
df['type'] = df['type'].fillna('Unknown')
df['available'] = df['available'].fillna(df['available'].median())
df['availableText'] = df['availableText'].fillna('Unknown')
df['sold'] = df['sold'].fillna(df['sold'].median())
df['lastUpdated'] = df['lastUpdated'].fillna('Unknown')

In [80]:
df.isnull().sum()

brand                0
title                0
type                 0
price                0
priceWithCurrency    0
available            0
availableText        0
sold                 0
lastUpdated          0
itemLocation         0
dtype: int64

In [81]:
df.duplicated().sum()

np.int64(0)

In [82]:
df.describe()

             price    available          sold
count  1000.000000  1000.000000   1000.000000
mean     46.481200    18.931000    761.966000
std      35.527862    58.113832   3191.825227
min       3.000000     2.000000      1.000000
25%      22.990000     5.000000     14.000000
50%      35.710000    10.000000     49.500000
75%      59.000000    10.000000    313.750000
max     259.090000   842.000000  54052.000000

In [83]:
input_X = df.drop('price', axis=1)
output_y = df['price']
input_X.shape,output_y.shape

((1000, 9), (1000,))

In [84]:
encoded_input_X = pd.get_dummies(input_X)
encoded_input_X

,available,sold,brand_2nd To None,brand_AS PHOTOS,brand_AS PICTURE SHOWN,brand_AS SHOW,brand_AS SHOWN,brand_AXE,brand_Abercrombie & Fitch,brand_Acqua Di Gio,...,"itemLocation_West Harrison, Indiana, United States","itemLocation_West Orange, New Jersey, United States","itemLocation_Westminster, California, United States","itemLocation_Whittier, California, United States","itemLocation_Windsor Mill, Maryland, United States","itemLocation_Winter Garden, Florida, United States","itemLocation_Winter Haven, Florida, United States","itemLocation_Woodbridge, Virginia, United States","itemLocation_Wynnewood, Pennsylvania, United States","itemLocation_shanghai, China"
0,10.0,116.0,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,8.0,48.0,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,10.0,27.0,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,2.0,159.0,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,10.0,156.0,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,45.0,1613.0,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
996,10.0,31.0,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
997,2.0,305.0,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
998,2.0,22.0,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
999,10.0,24.0,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [85]:
encoded_input_X = encoded_input_X.astype('int')
encoded_input_X

,available,sold,brand_2nd To None,brand_AS PHOTOS,brand_AS PICTURE SHOWN,brand_AS SHOW,brand_AS SHOWN,brand_AXE,brand_Abercrombie & Fitch,brand_Acqua Di Gio,...,"itemLocation_West Harrison, Indiana, United States","itemLocation_West Orange, New Jersey, United States","itemLocation_Westminster, California, United States","itemLocation_Whittier, California, United States","itemLocation_Windsor Mill, Maryland, United States","itemLocation_Winter Garden, Florida, United States","itemLocation_Winter Haven, Florida, United States","itemLocation_Woodbridge, Virginia, United States","itemLocation_Wynnewood, Pennsylvania, United States","itemLocation_shanghai, China"
0,10,116,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,8,48,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,10,27,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,2,159,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,10,156,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,45,1613,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
996,10,31,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
997,2,305,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
998,2,22,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
999,10,24,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [86]:
numeric_col = ['available','sold']
scaler = StandardScaler()
encoded_input_X[numeric_col] = scaler.fit_transform(encoded_input_X[numeric_col])
encoded_input_X

,available,sold,brand_2nd To None,brand_AS PHOTOS,brand_AS PICTURE SHOWN,brand_AS SHOW,brand_AS SHOWN,brand_AXE,brand_Abercrombie & Fitch,brand_Acqua Di Gio,...,"itemLocation_West Harrison, Indiana, United States","itemLocation_West Orange, New Jersey, United States","itemLocation_Westminster, California, United States","itemLocation_Whittier, California, United States","itemLocation_Windsor Mill, Maryland, United States","itemLocation_Winter Garden, Florida, United States","itemLocation_Winter Haven, Florida, United States","itemLocation_Woodbridge, Virginia, United States","itemLocation_Wynnewood, Pennsylvania, United States","itemLocation_shanghai, China"
0,-0.153758,-0.202482,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,-0.188190,-0.223797,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,-0.153758,-0.230379,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,-0.291488,-0.189003,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,-0.153758,-0.189943,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,0.448810,0.266764,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
996,-0.153758,-0.229126,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
997,-0.291488,-0.143238,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
998,-0.291488,-0.231947,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
999,-0.153758,-0.231320,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [87]:
X_train,X_test,y_train,y_test = train_test_split(encoded_input_X,output_y,test_size=0.20,random_state=42)
X_train

,available,sold,brand_2nd To None,brand_AS PHOTOS,brand_AS PICTURE SHOWN,brand_AS SHOW,brand_AS SHOWN,brand_AXE,brand_Abercrombie & Fitch,brand_Acqua Di Gio,...,"itemLocation_West Harrison, Indiana, United States","itemLocation_West Orange, New Jersey, United States","itemLocation_Westminster, California, United States","itemLocation_Whittier, California, United States","itemLocation_Windsor Mill, Maryland, United States","itemLocation_Winter Garden, Florida, United States","itemLocation_Winter Haven, Florida, United States","itemLocation_Woodbridge, Virginia, United States","itemLocation_Wynnewood, Pennsylvania, United States","itemLocation_shanghai, China"
29,-0.153758,-0.229439,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
535,0.052837,-0.238216,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
695,-0.170974,-0.236962,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
557,-0.239839,-0.230066,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
836,-0.274272,-0.236648,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,-0.291488,-0.237589,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
270,-0.222623,-0.234454,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
860,-0.257055,-0.238216,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
435,-0.153758,-0.094652,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
102,-0.153758,-0.189630,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [88]:
X_test

,available,sold,brand_2nd To None,brand_AS PHOTOS,brand_AS PICTURE SHOWN,brand_AS SHOW,brand_AS SHOWN,brand_AXE,brand_Abercrombie & Fitch,brand_Acqua Di Gio,...,"itemLocation_West Harrison, Indiana, United States","itemLocation_West Orange, New Jersey, United States","itemLocation_Westminster, California, United States","itemLocation_Whittier, California, United States","itemLocation_Windsor Mill, Maryland, United States","itemLocation_Winter Garden, Florida, United States","itemLocation_Winter Haven, Florida, United States","itemLocation_Woodbridge, Virginia, United States","itemLocation_Wynnewood, Pennsylvania, United States","itemLocation_shanghai, China"
521,-0.153758,-0.225364,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
737,-0.153758,-0.230379,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
740,0.087269,-0.223797,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
660,-0.257055,-0.237902,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
411,1.257972,0.180249,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
408,-0.153758,-0.235708,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
332,-0.222623,-0.236022,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
208,-0.153758,0.452644,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
613,0.483242,-0.212199,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
78,-0.274272,-0.237902,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [89]:
model_lr = LinearRegression()
model_lr.fit(X_train,y_train)

LinearRegression()

In [93]:
model_lr.predict(X_test)

array([ 48.77328944,  72.39485529,  33.21019339,  48.06367077,
        33.54335351,  43.23782255,  35.71976564,  29.69014707,
        38.79405882,  28.49465191,  41.62703093,  -0.23588671,
        41.39941773,  41.80068573,  32.36614287,  84.43989168,
        22.01928311,  44.1842203 ,  41.20782648,  54.02602755,
        51.23579681,  52.23770012,  52.43571522,  69.14424478,
        24.60375864,  85.36519463,  77.8214591 ,  35.12882603,
        70.40874529,  46.12091054,  74.72123368,  51.54203615,
        63.76187389,  33.15010996,  24.13394544,  45.40867328,
        54.6233574 ,  84.81934262,  55.94394377,  21.4222675 ,
        73.34263557,  51.12976758,  40.52243979,  48.93986793,
        34.94643705,  53.18346014,  30.43971025, 105.88722564,
        20.85843066,  43.76815111,  79.0234196 ,  41.06959029,
        34.38255518,  46.80649959,  20.03171717,  60.57271294,
        42.3012739 ,  26.87653837,  31.37228511,  56.05631824,
        71.88708128,  76.60774978,  81.02821441,  79.1411192 ,
        42.74801937,  39.74865725,  50.15417366,  25.73579864,
        33.00747833,  39.28529517,  51.68229931,  99.78120355,
        65.28505333,  30.85103361,  46.81490712,  19.02167804,
        29.73208293,  13.93681357,  32.65061984,  40.28272379,
        41.27776039,  23.81313035,  64.82799686,  30.77554736,
        24.17139475,  61.86201736,  13.17316064,  45.57553396,
        70.65019193,  23.35015779,  41.77955667,  25.18363805,
        43.29817563, 102.61333465,  46.42286789,  35.4583539 ,
        47.7614696 ,  30.21493955,  67.74805619,  42.51325134,
        38.57282958,  34.4050208 ,  48.271233  ,  44.44628749,
        28.57493317,  52.99833681,  46.37254177,  47.49117163,
        24.778358  ,  55.2814699 ,  45.23955748,  46.78408731,
        52.37247943,  61.70421875,  78.62152928,  34.50359871,
        19.15089002,  63.80649295,  48.15183133,  64.23567644,
        36.11288219,  44.14534168,  45.15428207,  28.97673449,
        22.50195481,  24.17171046,  44.05694963,  42.92688094,
        53.57565376,  77.51124422,  41.60222976,  27.5469847 ,
        55.08961043,  31.41638637,  49.77711221,  66.83484678,
        51.44895543,  29.46115764,  83.28174512,  44.27355641,
        31.0268489 ,  41.1385873 ,  67.18640433,  69.73416715,
        32.86933564,  53.69014056,  50.57853168,  40.82449927,
        59.494873  ,  55.16630045,  51.04579403,  29.31666988,
        43.37563761,  33.06886701,  61.11475702,  76.96570199,
        31.11176291,  42.28175124,  15.67744892,  64.87690168,
        44.51112271,  54.12945675,  42.48826454,  58.44434234,
        39.10813898,  72.75016868,  58.75372945,  51.17007868,
        50.35519635,  48.58527584,  40.88299299,  30.78628946,
        53.78959932,  30.65213949,  38.88753913,  63.18077311,
        43.31278529,  43.97229621,  40.34162931,  24.86875865,
        60.37069427,  23.44990422,  26.13767431,  54.70015426,
        20.50108779,  59.17886036,  35.62418282,  50.90918639,
        43.89961952,  30.70334778,  41.94566586,  47.32535729,
        62.08767442,  41.1105076 ,  31.03305445,  28.0720718 ,
        32.59565751,  49.02713975,  42.22964894,  28.29930644])

In [94]:
y_test

521    29.46
737    78.99
740    59.63
660    67.50
411    26.00
       ...
408    23.99
332    23.00
208    54.91
613    32.13
78     26.50
Name: price, Length: 200, dtype: float64

In [96]:
r2_score(y_test,model_lr.predict(X_test))

0.37203105210342735